name: Do the Thing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  mirror-static-endpoints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Fetch # the current API response, pipe it through jq and into a new file named with today's date
        run: ./do-the-thing.sh"
      # Compare with current file
      # If there is any diff, rename existing current to yesterday's date, copy today's file to current
      - name: Commit # the changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update API responses"
          git push
